//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeDatos
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class DelegacionesMunicipale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DelegacionesMunicipale()
        {
            this.Reportes = new ObservableCollection<Reporte>();
            this.Usuarios = new ObservableCollection<Usuario>();
        }
    
        public int idDelegacion { get; set; }
        public string nombre { get; set; }
        public int numero { get; set; }
        public string colonia { get; set; }
        public string calle { get; set; }
        public int codigoPostal { get; set; }
        public string correo { get; set; }
        public string telefono { get; set; }
        public string municipio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Reporte> Reportes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Usuario> Usuarios { get; set; }
    }
}
